name: twa
channels:
  - conda-forge
  - anaconda
  - bioconda
  - r
  - defaults
dependencies:
  - _ipython_minor_entry_point=8.7.0
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.3.1
  - appnope=0.1.3
  - asttokens=2.2.1
  - async-timeout=4.0.2
  - attrs=22.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blinker=1.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cachetools=5.2.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.0.6
  - cryptography=38.0.4
  - cycler=0.11.0
  - dataclasses=0.8
  - debugpy=1.6.4
  - decorator=5.1.1
  - docker-pycreds=0.4.0
  - entrypoints=0.4
  - executing=1.2.0
  - fonttools=4.38.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2022.11.0
  - functorch=0.2.0
  - gitdb=4.0.10
  - gitpython=3.1.29
  - google-auth=2.15.0
  - google-auth-oauthlib=0.4.6
  - grpcio=1.51.1
  - idna=3.4
  - importlib-metadata=5.2.0
  - ipykernel=6.19.4
  - ipython=8.7.0
  - jedi=0.18.2
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=7.4.8
  - jupyter_core=5.1.0
  - kiwisolver=1.4.4
  - lcms2=2.14
  - lerc=4.0.0
  - libabseil=20220623.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=14.0.6
  - libdeflate=1.14
  - libffi=3.4.2
  - libgfortran
  - libgfortran5
  - libgrpc=1.51.1
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.21.11
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libtiff=4.5.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libzlib=1.2.13
  - lightning-bolts=0.6.0.post1
  - lightning-utilities=0.5.0
  - llvm-openmp=15.0.6
  - llvmlite=0.39.1
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mkl=2022.2.1
  - multidict=6.0.2
  - munkres=1.1.4
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - ninja=1.11.0
  - numba=0.56.4
  - numpy=1.23.5
  - notebook=6.5.3
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openssl=3.0.7
  - packaging=22.0
  - pandas=1.5.2
  - parso=0.8.3
  - pathtools=0.1.2
  - patsy=0.5.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=20.2
  - platformdirs=2.6.0
  - promise=2.3
  - prompt-toolkit=3.0.36
  - protobuf=4.21.11
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.13.0
  - pyjwt=2.6.0
  - pyopenssl=22.1.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.8
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=1.12.1
  - pytorch-lightning=1.8.1
  - pytz=2022.7
  - pyu2f=0.1.5
  - pyyaml=6.0
  - pyzmq=24.0.1
  - re2=2022.06.01
  - readline=8.1.2
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.7
  - scikit-learn=1.2.0
  - scipy=1.9.3
  - seaborn=0.12.1
  - seaborn-base=0.12.1
  - sentry-sdk=1.12.1
  - setproctitle=1.3.2
  - setuptools=65.6.3
  - shortuuid=1.0.11
  - six=1.16.0
  - sleef=3.5.1
  - smmap=3.0.5
  - stack_data=0.6.2
  - statsmodels=0.13.5
  - tbb=2021.7.0
  - tensorboard=2.11.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - torchdiffeq=0.2.2
  - torchmetrics=0.11.0
  - torchvision=0.15.2
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.8.0
  - typing=3.10.0.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - unicodedata2=15.0.0
  - urllib3=1.26.13
  - wandb=0.13.7
  - wcwidth=0.2.5
  - werkzeug=2.2.2
  - wheel=0.38.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.8.1
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - ipywidgets=8.0.7
  - scanpy=1.9.3
  - igraph=0.10.3
  - leidenalg=0.9.1
  - pip:
      - git+https://github.com/nitzanlab/phase2vec
      - git+https://github.com/theislab/scvelo
      - git+https://github.com/j-bac/scikit-dimension
